services:
  backend:
    build:
      context: ./backend
    ports: 
      - 8000:8000
    depends_on: 
      db:
        condition: service_healthy
  
  db:
    image: mysql:latest
    ports: 
    - 3306:3306
    environment:
      - MYSQL_DATABASE=base
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55