FROM python:3.12
WORKDIR /code

COPY pyproject.toml poetry.lock ./
COPY app app

RUN pip install --no-cache --upgrade poetry
RUN poetry install --no-root --only  main


CMD ["poetry", "run", "uvicorn","--host","0.0.0.0","app.main:app"]
